source 'https://rubygems.org'

gem 'active_model_serializers'
gem 'bcrypt', '~> 3.1.7'
gem 'clockwork'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'delayed_job_recurring'
gem 'pg'
gem 'pry', '~> 0.10.1'
gem 'pry-rails'
gem 'puma'
gem 'rack-cors', :require => 'rack/cors'
gem 'rails', '4.2.3'
gem 'rails_12factor'
gem 'rails-api'
gem 'twilio-ruby', '~> 3.12'

group :development, :test do
  gem 'byebug'
  gem 'delayed_job_active_record'
  gem 'delayed_job_recurring'
  gem 'dotenv-rails'
  gem 'hirb'
  gem 'spring'
end
